dataset:
  data_path: data
  dev_ratio: 0.2
  has_node_feat: false
  is_overwrite_precompute: false
  is_sample_subgraph: true
  is_save_split: false
  name: Youshu
  node_order: DFS
  num_bundles: 100
  num_fwd_pass: 1
  num_items: 3597
  num_subgraph_batch: 2
  num_users: 88
  test_loader_name: TestData
  train_loader_name: TrainData
  train_ratio: 0.8
device: cuda:0
exp_dir: exp/BGGN
exp_name: Youshu_20220410_095332_22820
gpus:
- 0
model:
  block_size: 1
  dimension_reduce: true
  edge_weight: 1.0
  embedding_dim: 64
  has_attention: true
  hidden_dim: 64
  is_sym: true
  item_embedding_dim: 64
  max_num_nodes: 300
  name: BGGNMixtureBernoulli
  num_GNN_layers: 2
  num_GNN_prop: 1
  num_canonical_order: 1
  num_mix_component: 20
  sample_stride: 1
  user_embedding_dim: 64
run_id: '22820'
runner: BggnRunner
save_dir: exp/BGGN\Youshu_20220410_095332_22820
seed: 1234
test:
  batch_size: 1
  better_vis: true
  is_single_plot: false
  is_test_ER: false
  is_vis: true
  num_test_gen: 183
  num_vis: 20
  num_workers: 16
  test_model_dir: exp/BGGN\Youshu_20220410_095332_22820
  test_model_name: model_snapshot_0000050.pth
  topk: 10
  topk1: 5
  vis_num_row: 5
train:
  batch_size: 64
  bpr_weight: 1
  display_iter: 100
  is_resume: false
  lr: 1.0
  lr_decay: 0.1
  lr_decay_epoch:
  - 100000000
  lr_decay_size: 1
  max_epoch: 50
  momentum: 0.9
  num_workers: 16
  optimizer: Adam
  resume_dir: exp/BGGN
  resume_epoch: 5000
  resume_model: model_snapshot_0005000.pth
  shuffle: true
  snapshot_epoch: 5
  tsne_dir: ./tsne
  valid_epoch: 50
  wd: 0.0
use_gpu: true
use_horovod: false
